// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // CHANGED: Return web config instead of throwing error
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjL_5RUu59wCiKMZHg2Nw4LGvF3e7Y_NA',
    appId: '1:542793890474:web:100a9d534aec10f3c02ed3',
    messagingSenderId: '542793890474',
    projectId: 'personal-test-e529b',
    authDomain: 'personal-test-e529b.firebaseapp.com',
    storageBucket: 'personal-test-e529b.firebasestorage.app',
    measurementId: 'G-GFG2XW2GW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEyXbXqbVk8Fo_f1rrhAdUwaX1CLZCbK0',
    appId: '1:542793890474:android:968f34ece92ef546c02ed3',
    messagingSenderId: '542793890474',
    projectId: 'personal-test-e529b',
    storageBucket: 'personal-test-e529b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZLHxEABJj77gEREbYZzraB2gsgaZIl4',
    appId: '1:542793890474:ios:29d2ad5da1c8307cc02ed3',
    messagingSenderId: '542793890474',
    projectId: 'personal-test-e529b',
    storageBucket: 'personal-test-e529b.firebasestorage.app',
    iosBundleId: 'com.example.seniorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgZLHxEABJj77gEREbYZzraB2gsgaZIl4',
    appId: '1:542793890474:ios:29d2ad5da1c8307cc02ed3',
    messagingSenderId: '542793890474',
    projectId: 'personal-test-e529b',
    storageBucket: 'personal-test-e529b.firebasestorage.app',
    iosBundleId: 'com.example.seniorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjL_5RUu59wCiKMZHg2Nw4LGvF3e7Y_NA',
    appId: '1:542793890474:web:117d0b27594447d7c02ed3',
    messagingSenderId: '542793890474',
    projectId: 'personal-test-e529b',
    authDomain: 'personal-test-e529b.firebaseapp.com',
    storageBucket: 'personal-test-e529b.firebasestorage.app',
    measurementId: 'G-D69M51XK7Y',
  );

}